drop table if exists users CASCADE;
create table users
(
    id          bigint generated by default as identity,
    email       varchar(45),
    password    varchar(100),
    nickname    varchar(45),
    primary key (id)
);

drop table if exists refresh_token CASCADE;
create table refresh_token
(
    user_id     bigint generated by default as identity,
    refresh_token    varchar(300),
    primary key (user_id)
);